# Generated by Django 4.2 on 2023-06-07 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontact",
            name="user_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entitycontact",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contacts.address",
            ),
        ),
        migrations.AddField(
            model_name="entitycontact",
            name="entity_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact",
                to="entities.entity",
            ),
        ),
        migrations.AddField(
            model_name="branchcontact",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contacts.address",
            ),
        ),
        migrations.AddField(
            model_name="branchcontact",
            name="branch_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact",
                to="entities.branch",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="address",
                to="entities.branch",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="address",
                to="entities.entity",
            ),
        ),
    ]
