# Generated by Django 4.2.2 on 2023-06-30 03:46

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("old_id", models.IntegerField()),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("science", "Science"),
                            ("student", "Student"),
                            ("external", "External"),
                            ("core_function", "Core Function"),
                        ],
                        help_text="The project type determines the approval and                     documentation requirements during the project's                     life span. Choose wisely - you will not be able                     to change the project type later.                     If you get it wrong, create a new project of the                     correct type and tell admins to delete the duplicate                     project of the incorrect type.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("pending", "Pending Project Plan"),
                            ("active", "Active (Approved)"),
                            ("updating", "Update Requested"),
                            ("closure_requested", "Closure Requested"),
                            ("closing", "Closure Pending Final Update"),
                            ("final_update", "Final Update Requested"),
                            ("completed", "Completed and Closed"),
                            ("terminated", "Terminated and Closed"),
                            ("suspended", "Suspended"),
                        ],
                        default="new",
                        max_length=50,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        default=2023,
                        help_text="The project year with four digits, e.g. 2014",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        default=projects.models.get_next_available_number_for_year,
                        help_text="The running project number within the project year.",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("tagline", models.CharField(max_length=500)),
                ("keywords", models.CharField(max_length=500)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResearchFunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "association",
                    models.TextField(
                        blank=True,
                        help_text="The research function's association with departmental programs/divisions.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this research function has been deprecated or not.",
                    ),
                ),
                ("old_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "Research Function",
                "verbose_name_plural": "Research Functions",
            },
        ),
    ]
