# Generated by Django 4.2 on 2023-04-21 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("medias", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="core_function_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="projects.corefunctionproject",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="external_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="projects.externalproject",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="science_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="projects.scienceproject",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="student_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="projects.studentproject",
            ),
        ),
    ]
