# Generated by Django 4.2.2 on 2023-07-07 08:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agencies", "0001_initial"),
        ("medias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="The publication year of this report with four digits, e.g. 2014 for the ARAR 2013-2014",
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(2013)],
                        verbose_name="Report Year",
                    ),
                ),
                (
                    "dm",
                    models.TextField(
                        blank=True,
                        help_text="Directors's message (less than 10,000 words)",
                        null=True,
                        verbose_name="Director's Message",
                    ),
                ),
                (
                    "service_delivery_intro",
                    models.TextField(
                        blank=True,
                        help_text="Introductory paragraph for the Science Delivery Structure section in the ARAR",
                        null=True,
                        verbose_name="Service Deilvery Structure",
                    ),
                ),
                (
                    "research_intro",
                    models.TextField(
                        blank=True,
                        help_text="Introduction paragraph for the Research Activity section in the ARAR",
                        null=True,
                        verbose_name="Research Activities Intro",
                    ),
                ),
                (
                    "student_intro",
                    models.TextField(
                        blank=True,
                        help_text="Introduction paragraph for the Student Projects section in the ARAR",
                        null=True,
                        verbose_name="Student Projects Introduction",
                    ),
                ),
                (
                    "publications",
                    models.TextField(
                        blank=True,
                        help_text="Publications for the year",
                        null=True,
                        verbose_name="Publications and Reports",
                    ),
                ),
                (
                    "date_open",
                    models.DateField(
                        help_text="The date at which submissions are opened for this report"
                    ),
                ),
                (
                    "date_closed",
                    models.DateField(
                        help_text="The date at which submissions are closed for this report"
                    ),
                ),
                (
                    "collaborations_chapter_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collaborations_chapter_image",
                        to="medias.annualreportimage",
                    ),
                ),
                (
                    "cover_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="The cover page for the document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cover_page",
                        to="medias.annualreportimage",
                    ),
                ),
                (
                    "divisions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Divisions included in this report",
                        related_name="reports_in",
                        to="agencies.division",
                    ),
                ),
                (
                    "partnerships_chapter_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partnerships_chapter_image",
                        to="medias.annualreportimage",
                    ),
                ),
                (
                    "pdf",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="The PDF file generated for the report.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="medias.reportpdf",
                    ),
                ),
                (
                    "publications_chapter_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications_chapter_image",
                        to="medias.annualreportimage",
                    ),
                ),
                (
                    "rear_cover_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="The back page for the document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rear_cover_page",
                        to="medias.annualreportimage",
                    ),
                ),
                (
                    "research_chapter_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_chapter_image",
                        to="medias.annualreportimage",
                    ),
                ),
                (
                    "sds_chapter_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sds_chapter_image",
                        to="medias.annualreportimage",
                    ),
                ),
                (
                    "service_delivery_chart",
                    models.ForeignKey(
                        blank=True,
                        help_text="The 'Service Delivery Structure' page image (2480pt, 2480pt).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_delivery_chart",
                        to="medias.annualreportimage",
                    ),
                ),
                (
                    "studentprojects_chapter_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_projects_chapter_image",
                        to="medias.annualreportimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annual Report",
                "verbose_name_plural": "Annual Reports",
            },
        ),
    ]
