# Generated by Django 4.2.2 on 2023-06-23 13:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agencies", "0001_initial"),
        ("medias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ARARReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "year",
                    models.DateField(
                        help_text="The publication year of this report with four digits, e.g. 2014 for the ARAR 2013-2014",
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(2013)],
                        verbose_name="Report Year",
                    ),
                ),
                (
                    "dm",
                    models.TextField(
                        blank=True,
                        help_text="Directors's message (less than 10,000 words)",
                        null=True,
                        verbose_name="Director's Message",
                    ),
                ),
                (
                    "service_delivery_intro",
                    models.TextField(
                        blank=True,
                        help_text="Introductory paragraph for the Science Delivery Structure section in the ARAR",
                        null=True,
                        verbose_name="Service Deilvery Structure",
                    ),
                ),
                (
                    "coverpage",
                    models.ForeignKey(
                        blank=True,
                        help_text="The cover page for the document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="medias.coverpage",
                    ),
                ),
                (
                    "divisions",
                    models.ForeignKey(
                        blank=True,
                        help_text="Divisions included in this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="agencies.division",
                    ),
                ),
                (
                    "pdf",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="The PDF file generated for the report.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="medias.ararpdf",
                    ),
                ),
                (
                    "rearcoverpage",
                    models.ForeignKey(
                        blank=True,
                        help_text="The back page for the document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="medias.rearpage",
                    ),
                ),
                (
                    "service_delivery_chart",
                    models.ForeignKey(
                        blank=True,
                        help_text="The 'Service Delivery Structure' page image (2480pt, 2480pt).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="medias.servicedeliveryimage",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ARAR Reports",
            },
        ),
    ]
