# Generated by Django 4.2.2 on 2023-07-09 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnnualReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("old_id", models.IntegerField()),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="The publication year of this report with four digits, e.g. 2014 for the ARAR 2013-2014",
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(2013)],
                        verbose_name="Report Year",
                    ),
                ),
                (
                    "dm",
                    models.TextField(
                        blank=True,
                        help_text="Directors's message (less than 10,000 words)",
                        null=True,
                        verbose_name="Director's Message",
                    ),
                ),
                (
                    "service_delivery_intro",
                    models.TextField(
                        blank=True,
                        help_text="Introductory paragraph for the Science Delivery Structure section in the ARAR",
                        null=True,
                        verbose_name="Service Deilvery Structure",
                    ),
                ),
                (
                    "research_intro",
                    models.TextField(
                        blank=True,
                        help_text="Introduction paragraph for the Research Activity section in the ARAR",
                        null=True,
                        verbose_name="Research Activities Intro",
                    ),
                ),
                (
                    "student_intro",
                    models.TextField(
                        blank=True,
                        help_text="Introduction paragraph for the Student Projects section in the ARAR",
                        null=True,
                        verbose_name="Student Projects Introduction",
                    ),
                ),
                (
                    "publications",
                    models.TextField(
                        blank=True,
                        help_text="Publications for the year",
                        null=True,
                        verbose_name="Publications and Reports",
                    ),
                ),
                (
                    "date_open",
                    models.DateField(
                        help_text="The date at which submissions are opened for this report"
                    ),
                ),
                (
                    "date_closed",
                    models.DateField(
                        help_text="The date at which submissions are closed for this report"
                    ),
                ),
            ],
            options={
                "verbose_name": "Annual Report",
                "verbose_name_plural": "Annual Reports",
            },
        ),
    ]
