# Generated by Django 4.2 on 2023-05-25 04:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ararreport",
            options={"verbose_name_plural": "ARAR Reports"},
        ),
    ]
