# Generated by Django 4.2.2 on 2023-07-10 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentreportdetail",
            name="report",
            field=models.ForeignKey(
                blank=True,
                help_text="The annual report publishing this StudentReport",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reports.annualreport",
            ),
        ),
        migrations.AddField(
            model_name="projectplandetail",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_plan_details",
                to="documents.projectdocument",
            ),
        ),
    ]
