# Generated by Django 4.2.1 on 2023-05-25 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="researchfunction",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                help_text="The scientist in charge of the Research Function",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="research_functions_led",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Function Leader",
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                help_text="The Approver receives notifications about outstanding requests and has permission             to approve documents. The approver can be anyone in a supervisory role, including the Director.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="divisions_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="director",
            field=models.ForeignKey(
                blank=True,
                help_text="The Division's director is attributed as head of the Division in reports",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="divisions_led",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="businessarea",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_areas_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="businessarea",
            name="data_custodian",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_area_data_handled",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="businessarea",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_areas_led",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="businessarea",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_areas_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
