# Generated by Django 4.2 on 2023-04-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                ("slug", models.CharField(max_length=20)),
                ("focus", models.CharField(max_length=250)),
                ("introduction", models.TextField()),
                ("published", models.BooleanField(default=False)),
                ("effective_from", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
