# Generated by Django 4.2.2 on 2023-06-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DBCARegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=50)),
                ("long", models.CharField(blank=True, max_length=50, null=True)),
                ("lat", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=50)),
                ("long", models.CharField(blank=True, max_length=50, null=True)),
                ("lat", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IBRARegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=50)),
                ("long", models.CharField(blank=True, max_length=50, null=True)),
                ("lat", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IMCRARegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=50)),
                ("long", models.CharField(blank=True, max_length=50, null=True)),
                ("lat", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NaturalResourceManagementRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=50)),
                ("long", models.CharField(blank=True, max_length=50, null=True)),
                ("lat", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="A human-readable, short but descriptive name.",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("relevantarea", "Relevant Area"),
                            ("dbcaregion", "DBCA Region"),
                            ("dbcadistrict", "DBCA District"),
                            (
                                "ibra",
                                "IBRA Region (Interim Biogeographic Regionalisation for Australia)",
                            ),
                            (
                                "imcra",
                                "IMCRA Region (Integrated Marine and Coastal Regionalisation of Australia)",
                            ),
                            ("nrm", "Natural Resource Management Region"),
                        ],
                        default="relevantarea",
                        max_length=25,
                        verbose_name="Area Type",
                    ),
                ),
                (
                    "source_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="The Source ID", null=True
                    ),
                ),
                ("old_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "Project Area",
                "verbose_name_plural": "Project Areas",
            },
        ),
    ]
