# Generated by Django 4.2 on 2023-06-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotereport",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
